from typing import Protocol, TypedDict

class AppendResult(TypedDict):
    context_id: str
    request_id: str | None
    first_sequence: int | None
    last_sequence: int | None
    event_count: int
    replayed: bool
    payload_hash: str

class CompactionRecord(TypedDict):
    context_id: str
    compaction_id: str
    snapshot_sequence: int
    latest_sequence_at_read: int
    stale: bool
    result_schema_version: int
    result_json: str
    created_at: str

class ContextStore(Protocol):
    def create(self, context_id: str | None = None) -> str: ...
    def append(self, context_id: str, events: list[dict], request_id: str | None = None) -> AppendResult: ...
    def load_events(self, context_id: str) -> list[dict]: ...
    def save_compaction(self, context_id: str, result: CompactionRecord) -> None: ...
    def get_latest_compaction(self, context_id: str) -> CompactionRecord | None: ...
    def get_receipt(self, context_id: str, node_id: str) -> dict: ...
    def delete(self, context_id: str) -> None: ...
    def exists(self, context_id: str) -> bool: ...
    def touch(self, context_id: str) -> None: ...
    def get_metadata(self, context_id: str) -> dict: ...
