# tests/test_probes.py
"""Expanded probe-based evaluation suite.

Contains tests for Recall, Artifact-tracking, Continuation, and Decision probes,
each designed to assert key semantic correctness invariants and catch specific
context compaction failure modes.
"""

from __future__ import annotations

import os
import pytest
from trace_gc import TraceGC, compact_events
from trace_gc.events import load_events_from_json

FIXTURE_PATH = os.path.join(os.path.dirname(__file__), "fixtures", "sample_trace.json")


def test_recall_probe():
    """Recall probe test.
    
    Verifies that the final compacted prompt correctly retains critical, successful
    decisions/outcomes (such as 'Task complete' and 'token bucket') while ensuring 
    that obsolete and abandoned concepts (like 'FixedWindowLimiter' or the 
    fundamentally flawed fixed-window attempt) are completely pruned and do not 
    leak into the output prompt.
    
    Failure Mode Caught: 'Memory loss' / 'Over-pruning' where the compactor naively
    discards active, successful history and facts.
    """
    assert os.path.exists(FIXTURE_PATH), f"Fixture not found at {FIXTURE_PATH}"
    events = load_events_from_json(FIXTURE_PATH)
    result = compact_events(events)
    prompt = result["prompt"]

    # Assert critical final info is retained
    assert "Task complete" in prompt, "Compacted prompt lost final task status"
    assert "token bucket" in prompt, "Compacted prompt lost information on chosen algorithm"
    assert "bucket_capacity = 20" in prompt, "Compacted prompt lost active variable setting"

    # Assert abandoned branch contents did not leak
    assert "FixedWindowLimiter" not in prompt, "Obsolete FixedWindowLimiter leaked into prompt"
    assert "fixed-window" not in prompt, "Abandoned fixed-window concept leaked into prompt"


def test_artifact_tracking_probe_positive():
    """Artifact-tracking probe (positive case).
    
    Builds a trace where a tool produces a key artifact (a temporary file path)
    referenced by subsequent events on the active execution path. Verifies that the
    producing tool call and result events survive compaction.
    
    Failure Mode Caught: 'Memory hole' where critical identifiers or resources
    generated by tools are dropped, leaving downstream steps referencing non-existent
    entities.
    """
    client = TraceGC()
    
    # Trace where tool produces a temp file referenced by a later write
    client.add_event({"id": "e001", "type": "decision", "timestamp": 1000, "parent_id": None, "content": "Need temp file"})
    client.add_event({"id": "tc1", "type": "tool_call", "timestamp": 1010, "parent_id": "e001", "tool_name": "create_temp", "arguments": {}})
    client.add_event({"id": "tr1", "type": "tool_result", "timestamp": 1020, "parent_id": "tc1", "call_id": "tc1", "result": "/tmp/temp_99.txt"})
    client.add_event({"id": "e002", "type": "decision", "timestamp": 1030, "parent_id": "tr1", "content": "Writing config to /tmp/temp_99.txt"})
    
    res = client.compact()
    compact_ids = [ev["id"] for ev in res["compact_events"]]
    
    # Producing tool call and tool result must survive on the active path
    assert "tc1" in compact_ids, "Artifact producing tool call was pruned"
    assert "tr1" in compact_ids, "Artifact producing tool result was pruned"
    assert "/tmp/temp_99.txt" in res["prompt"], "Artifact path leaked/pruned from prompt"


def test_artifact_tracking_probe_adversarial():
    """Artifact-tracking probe (adversarial case).
    
    An artifact (database connection ID) is generated inside a branch that later
    gets abandoned. However, a later active cleanup step still references this ID.
    Verifies that the producing event is pruned (so the prompt remains clean), but
    its receipt is fully resolvable to recover the database connection ID on-demand.
    
    Failure Mode Caught: 'Dangling reference' / 'Orphaned state' where an abandoned
    branch's resources are completely lost, leaving cleanup or audit routines unable
    to resolve what was created.
    """
    client = TraceGC()
    
    # Main path
    client.add_event({"id": "e001", "type": "decision", "timestamp": 1000, "parent_id": None, "content": "Setup DB"})
    
    # Abandoned branch: attempts setup and creates conn_id "conn_42"
    client.add_event({"id": "a01", "type": "decision", "timestamp": 1010, "parent_id": "e001", "content": "Attempting setup"})
    client.add_event({"id": "tc1", "type": "tool_call", "timestamp": 1020, "parent_id": "a01", "tool_name": "connect_db", "arguments": {}})
    client.add_event({"id": "tr1", "type": "tool_result", "timestamp": 1030, "parent_id": "tc1", "call_id": "tc1", "result": "conn_42"})
    client.add_event({"id": "ab01", "type": "abandon", "timestamp": 1040, "parent_id": "tr1", "ref_to": ["a01"]})
    
    # Active continuation path references the abandoned connection for cleanup
    client.add_event({"id": "e002", "type": "decision", "timestamp": 1050, "parent_id": "e001", "content": "Database setup failed. Cleanup conn_42"})
    
    res = client.compact()
    compact_ids = [ev["id"] for ev in res["compact_events"]]
    
    # The tool result containing "conn_42" is inside the abandoned branch and must be pruned
    assert "tr1" not in compact_ids, "Pruning failed to remove abandoned tool result from active list"
    assert "tr1" in res["pruned_ids"], "Abandoned tool result was not added to pruned list"
    
    # The receipt for the pruned node must resolve to retrieve the db connection ID
    recovered = client.get_receipt("tr1")
    assert recovered["id"] == "tr1"
    assert recovered["result"] == "conn_42", "Failed to recover connection ID from receipt"


def test_continuation_probe():
    """Continuation probe.
    
    Builds a trace that ends mid-task (a multi-step server deployment plan).
    Verifies that the compacted output preserves the latest system status variable
    and the next steps, allowing an agent to resume correctly.
    
    Failure Mode Caught: 'Plan truncation' where compaction over-prunes current progress
    or active plan details, causing the agent to repeat steps or lose task context.
    """
    client = TraceGC()
    
    # Sequential deployment trace ending mid-task
    client.add_event({"id": "e001", "type": "decision", "timestamp": 1000, "parent_id": None, "content": "Deploying server"})
    client.add_event({"id": "e002", "type": "set_var", "timestamp": 1010, "parent_id": "e001", "key": "status", "value": "configuring"})
    client.add_event({"id": "tc1", "type": "tool_call", "timestamp": 1020, "parent_id": "e002", "tool_name": "write_config", "arguments": {}})
    client.add_event({"id": "tr1", "type": "tool_result", "timestamp": 1030, "parent_id": "tc1", "call_id": "tc1", "result": "config_written"})
    client.add_event({"id": "e003", "type": "set_var", "timestamp": 1040, "parent_id": "tr1", "key": "status", "value": "ready_to_boot"}) # overrides status='configuring'
    client.add_event({"id": "e004", "type": "decision", "timestamp": 1050, "parent_id": "e003", "content": "Configuration done. Ready to boot next."})
    
    res = client.compact()
    compact_ids = [ev["id"] for ev in res["compact_events"]]
    prompt = res["prompt"]
    
    # Latest status and next step decision must be preserved
    assert "e003" in compact_ids, "Latest status variable was pruned"
    assert "status = ready_to_boot" in prompt, "Compacted prompt lost current ready_to_boot status"
    assert "Ready to boot next" in prompt, "Compacted prompt lost current plan step"
    
    # Old status variable must be pruned
    assert "status = configuring" not in prompt, "Obsolete status value leaked into prompt"
    assert "e002" in res["pruned_ids"], "Obsolete status variable was not pruned"


def test_decision_probe():
    """Decision probe.
    
    Builds a trace with a clear decision point ("We chose approach B over A because A has a bug").
    Verifies that even when all unsuccessful tool calls/results inside branch A are pruned,
    the pivot decision and its rationale remain fully preserved in the compacted output.
    
    Failure Mode Caught: 'Rationale loss' where the reasoning behind a choice or pivot
    is discarded, causing the agent to repeat identical failed paths or loops.
    """
    client = TraceGC()
    
    # Trace showing a pivot from failed approach A to approach B
    client.add_event({"id": "e001", "type": "decision", "timestamp": 1000, "parent_id": None, "content": "Goal: parse JSON"})
    
    # Approach A attempt (failed/abandoned)
    client.add_event({"id": "a01", "type": "decision", "timestamp": 1010, "parent_id": "e001", "content": "Attempting regex parser"})
    client.add_event({"id": "tc1", "type": "tool_call", "timestamp": 1020, "parent_id": "a01", "tool_name": "run_regex", "arguments": {}})
    client.add_event({"id": "tr1", "type": "tool_result", "timestamp": 1030, "parent_id": "tc1", "call_id": "tc1", "result": "failed on nested objects"})
    client.add_event({"id": "ab01", "type": "abandon", "timestamp": 1040, "parent_id": "tr1", "ref_to": ["a01"]})
    
    # Pivot decision
    client.add_event({"id": "e002", "type": "decision", "timestamp": 1050, "parent_id": "e001", "content": "Regex parsing failed on nested objects. Pivoting to standard json library."})
    
    # Approach B attempt (succeeded)
    client.add_event({"id": "e003", "type": "decision", "timestamp": 1060, "parent_id": "e002", "content": "Attempting standard json library"})
    client.add_event({"id": "tc2", "type": "tool_call", "timestamp": 1070, "parent_id": "e003", "tool_name": "run_json_load", "arguments": {}})
    client.add_event({"id": "tr2", "type": "tool_result", "timestamp": 1080, "parent_id": "tc2", "call_id": "tc2", "result": "parsed_nested_json_successfully"})
    
    res = client.compact()
    compact_ids = [ev["id"] for ev in res["compact_events"]]
    prompt = res["prompt"]
    
    # Approach A detailed tool run must be pruned
    assert "tc1" not in compact_ids
    assert "tr1" not in compact_ids
    assert "run_regex" not in prompt, "Abandoned tool call leaked into compacted prompt"
    assert "RESULT failed on nested objects" not in prompt, "Abandoned failure result leaked into compacted prompt"
    
    # Pivot decision and rationale must remain fully preserved
    assert "e002" in compact_ids, "Pivot decision event was pruned"
    assert "Regex parsing failed on nested objects" in prompt, "Compacted prompt lost pivot rationale"
    assert "RESULT parsed_nested_json_successfully" in prompt, "Compacted prompt lost successful tool result content"
    assert any(ev["id"] == "tr2" and ev.get("result") == "parsed_nested_json_successfully" for ev in res["compact_events"]), "Successful tool result was not preserved in active list"


def test_cycle_collapse_receipt_probe(monkeypatch):
    """Cycle-collapse receipt probe.
    
    Exercises the `collapse_cycles` stage of the compaction pipeline. Because the public
    add_event() API enforces chronological parent-child validation, cycles can never be
    constructed under standard linear client usage. Therefore, this test monkeypatches 
    graph construction (`_build_state_graph`) to manually inject a sequence cycle 
    (c01 -> c02 -> c03 -> c01) and downstream continuation referencing the cycle output.
    
    Verifies that client.compact() successfully collapses the cycle into a single receipt 
    stub and get_receipt() correctly resolves the original members within that cluster.
    
    Failure Mode Caught: 'Opaque clusters' / 'Cycle data loss' where collapsing a
    cycle destroys the underlying event data, preventing downstream processes or
    debugging logs from resolving individual step payloads inside the cycle.
    """
    from trace_gc.graph import StateGraph
    import trace_gc.compactor
    from trace_gc.topo_sampler import _deterministic_cluster_id
    
    events = [
        {"id": "e001", "type": "decision", "timestamp": 1000, "content": "Start cycle test"},
        {"id": "c01", "type": "set_var", "timestamp": 1010, "key": "cap", "value": 5},
        {"id": "c02", "type": "tool_call", "timestamp": 1020, "tool_name": "test_capacity", "arguments": {"cap": 5}},
        {"id": "c03", "type": "tool_result", "timestamp": 1030, "call_id": "c02", "result": "too low"},
        {"id": "e002", "type": "decision", "timestamp": 1040, "content": "Cycle finished. References c03 output too low."}
    ]
    
    def mock_build_state_graph(evs):
        graph = StateGraph()
        for ev in evs:
            graph.add_node(ev)
        graph.add_edge("e001", "c01", "sequence")
        graph.add_edge("c01", "c02", "sequence")
        graph.add_edge("c02", "c03", "sequence")
        graph.add_edge("c03", "c01", "sequence")  # Completes cycle c03 -> c01
        graph.add_edge("c03", "e002", "sequence")
        return graph

    monkeypatch.setattr(trace_gc.compactor, "_build_state_graph", mock_build_state_graph)
    
    client = TraceGC()
    for ev in events:
        client.add_event(ev)
        
    res = client.compact()
    
    # Check that cycle members are pruned
    for cid in ["c01", "c02", "c03"]:
        assert cid in res["pruned_ids"]
        
    # Check that the cycle is collapsed into a single receipt stub in the prompt
    expected_cluster_id = _deterministic_cluster_id(["c01", "c02", "c03"])
    assert f"[RECEIPT {expected_cluster_id}]" in res["prompt"], "Cluster receipt stub was not rendered in prompt"
    
    # Verify we can resolve individual member events inside the collapsed cluster
    recovered = client.get_receipt("c02")
    assert recovered["id"] == "c02"
    assert recovered["tool_name"] == "test_capacity"
    assert recovered["arguments"] == {"cap": 5}
    assert recovered.get("pruned") is True
